---
name: Static Analysis

"on":
  pull_request:
  push:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter (HTML/CSS/JS/MD/YAML)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: (rss\.xml|sitemap\.xml)
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
